### PR TITLE
Update oneko.js

### PR DESCRIPTION
**Pull request by ImAFrogOwO**
# Fixed
- Issue where the kiddy element was placed under the topbars and got covered by the calls and settings div.

### CODE REVIEW

**Review by ImAFrogOwO — COMMENTED** [review]
fixed undefined direction

**Comment by adryd325** [comment]
i'm away right now, could you change the zindex to Number.MAX_VALUE

**Comment by ImAFrogOwO** [comment]
all good dw.
I didn't think of that at the time either. I tried Infinity but that broke it xD

**Review by ImAFrogOwO — COMMENTED** [review]
Changed `999999999` to `Number.MAX_VALUE`

**Pull request merged**
