### PR TITLE
Add Userscript

### PR DESCRIPTION
**Pull request by sjehuda**
This file (i.e. userscript) is installable with Userscript managers such as Greasemonkey, Falkon, Tampermonkey, Violentmonkey etc.

https://openuserjs.org/scripts/sjehuda/Oneko_WebMate

### CODE REVIEW

**Comment by aceArt-GmbH** [comment]
kitty

YouTubes `masthead-container` has a `z-index` of 2020.
Maybe kitty should have a higher z-index than 999?

**Comment by NotNite** [comment]
Uh... a GNOME extension? You [do know what this is inspired by](https://packages.debian.org/bullseye/games/oneko), right?

**Comment by adryd325** [comment]
Seems like a fun concept

I've also been asked to rewrite oneko.js to use requestAnimationFrame so that could be fun

**Comment by sjehuda** [comment]
On Tue, 16 May 2023 16:16:20 -0700
Julian ***@***.***> wrote:

> Uh... a GNOME extension? You [do know what this is inspired
> by](https://packages.debian.org/bullseye/games/oneko), right?
> 

Yes, but they work differently, and you program has different
image/skin type.

Yet, because GNOME Shell has Javascript support, it would be a matter
of a couple of hours, at most, to port your work to GNOME.

**Comment by adryd325** [comment]
I've linked out to your openuserjs listing in the readme

for now i'm gonna keep this repo only the base with the two modifications ive made as maintaining forks and other stuff is kinda tedious

**Pull request closed without merging**
